package ardaaydinkilinc.Cam_Sise.logistics.domain.vo;

/**
 * Status of a collection plan
 */
public enum PlanStatus {
    GENERATED("Generated by optimizer, not yet assigned"),
    ASSIGNED("Assigned to a vehicle"),
    IN_PROGRESS("Vehicle departed, collection in progress"),
    COMPLETED("Collection completed, vehicle returned"),
    CANCELLED("Plan cancelled");

    private final String description;

    PlanStatus(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public boolean canTransitionTo(PlanStatus newStatus) {
        return switch (this) {
            case GENERATED -> newStatus == ASSIGNED || newStatus == CANCELLED;
            case ASSIGNED -> newStatus == IN_PROGRESS || newStatus == CANCELLED;
            case IN_PROGRESS -> newStatus == COMPLETED || newStatus == CANCELLED;
            case COMPLETED, CANCELLED -> false;
        };
    }
}
