package ardaaydinkilinc.Cam_Sise.logistics.domain;

import ardaaydinkilinc.Cam_Sise.logistics.domain.event.*;
import ardaaydinkilinc.Cam_Sise.logistics.domain.vo.PlanStatus;
import ardaaydinkilinc.Cam_Sise.logistics.domain.vo.RouteStop;
import ardaaydinkilinc.Cam_Sise.shared.domain.base.AggregateRoot;
import ardaaydinkilinc.Cam_Sise.shared.domain.vo.Distance;
import ardaaydinkilinc.Cam_Sise.shared.domain.vo.Duration;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * CollectionPlan aggregate root
 * Represents an optimized collection route plan generated by CVRP optimizer
 */
@Entity
@Table(name = "collection_plans")
@Getter
@NoArgsConstructor
public class CollectionPlan extends AggregateRoot<Long> {

    @Column(name = "depot_id", nullable = false)
    private Long depotId;

    @Column(name = "assigned_vehicle_id")
    private Long assignedVehicleId;

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "kilometers", column = @Column(name = "total_distance_km"))
    })
    private Distance totalDistance;

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "minutes", column = @Column(name = "estimated_duration_minutes"))
    })
    private Duration estimatedDuration;

    @Column(name = "total_capacity_pallets")
    private Integer totalCapacityPallets;

    @Column(name = "total_capacity_separators")
    private Integer totalCapacitySeparators;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PlanStatus status;

    @Column(name = "planned_date")
    private LocalDate plannedDate;

    /**
     * Route stops stored as JSON or separate entity
     * For simplicity, using JSON column here
     */
    @Column(name = "route_stops_json", columnDefinition = "TEXT")
    private String routeStopsJson;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Factory method - created by CVRP optimizer
     */
    public static CollectionPlan generate(
            Long depotId,
            Distance totalDistance,
            Duration estimatedDuration,
            Integer totalCapacityPallets,
            Integer totalCapacitySeparators,
            LocalDate plannedDate,
            String routeStopsJson
    ) {
        CollectionPlan plan = new CollectionPlan();
        plan.depotId = depotId;
        plan.totalDistance = totalDistance;
        plan.estimatedDuration = estimatedDuration;
        plan.totalCapacityPallets = totalCapacityPallets;
        plan.totalCapacitySeparators = totalCapacitySeparators;
        plan.status = PlanStatus.GENERATED;
        plan.plannedDate = plannedDate;
        plan.routeStopsJson = routeStopsJson;
        plan.createdAt = LocalDateTime.now();
        plan.updatedAt = LocalDateTime.now();

        plan.addDomainEvent(new CollectionPlanGenerated(
                depotId,
                totalDistance,
                totalCapacityPallets,
                totalCapacitySeparators,
                plannedDate,
                LocalDateTime.now()
        ));

        return plan;
    }

    /**
     * Assign vehicle to this plan
     */
    public void assignVehicle(Long vehicleId) {
        if (!status.canTransitionTo(PlanStatus.ASSIGNED)) {
            throw new IllegalStateException("Cannot assign vehicle in status: " + status);
        }

        this.assignedVehicleId = vehicleId;
        this.status = PlanStatus.ASSIGNED;
        this.updatedAt = LocalDateTime.now();

        addDomainEvent(new RouteAssignedToVehicle(
                this.id,
                vehicleId,
                this.plannedDate,
                LocalDateTime.now()
        ));
    }

    /**
     * Start collection (vehicle departed)
     */
    public void start() {
        if (!status.canTransitionTo(PlanStatus.IN_PROGRESS)) {
            throw new IllegalStateException("Cannot start collection in status: " + status);
        }

        this.status = PlanStatus.IN_PROGRESS;
        this.updatedAt = LocalDateTime.now();

        addDomainEvent(new CollectionStarted(
                this.id,
                this.assignedVehicleId,
                this.depotId,
                LocalDateTime.now()
        ));
    }

    /**
     * Complete collection
     */
    public void complete(int actualPalletsCollected, int actualSeparatorsCollected) {
        if (!status.canTransitionTo(PlanStatus.COMPLETED)) {
            throw new IllegalStateException("Cannot complete collection in status: " + status);
        }

        this.status = PlanStatus.COMPLETED;
        this.updatedAt = LocalDateTime.now();

        addDomainEvent(new CollectionCompleted(
                this.id,
                this.assignedVehicleId,
                this.depotId,
                actualPalletsCollected,
                actualSeparatorsCollected,
                LocalDateTime.now()
        ));
    }

    /**
     * Cancel the plan
     */
    public void cancel() {
        if (!status.canTransitionTo(PlanStatus.CANCELLED)) {
            throw new IllegalStateException("Cannot cancel plan in status: " + status);
        }

        this.status = PlanStatus.CANCELLED;
        this.updatedAt = LocalDateTime.now();
        addDomainEvent(new CollectionPlanCancelled(this.id, LocalDateTime.now()));
    }

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
